require "rubygems"
require "fileutils"
require "ffi"

# Copied fom mkmf
def find_executable(bin, path = nil)
  executable_file = proc do |name|
    begin
      stat = File.stat(name)
    rescue SystemCallError
    else
      next name if stat.file? and stat.executable?
    end
  end

  if File.expand_path(bin) == bin
    return bin if executable_file.call(bin)
    return nil
  end
  path = %w[/usr/local/bin /usr/ucb /usr/bin /bin]
  if additional_path ||= ENV['PATH']
    path += additional_path.split(File::PATH_SEPARATOR)
  end
  file = nil
  path.each do |dir|
    return file if executable_file.call(file = File.join(dir, bin))
  end
  nil
end

def sys(cmd)
  puts " -- #{cmd}"
  unless ret = system(cmd)
    raise "ERROR: '#{cmd}' failed"
  end
  ret
end

desc "Build the fasttext shared lib"
task :compile_fasttext do
  # Do not attempt to install if we want to use the system fasttext lib
  next if ENV.key?("FASTTEXT_USE_SYSTEM_LIB") || ENV.key?("SKIP_FASTTEXT_COMPILE")

  if !find_executable("g++")
    abort "ERROR: g++ is required to build ffi-fasttext"
  end

  CWD = ::File.expand_path(::File.dirname(__FILE__))
  FASTTEXT_DIR = ::File.join(CWD, "..", "..", "..", "vendor", "fasttext")

  cppflags = "-c -O3 -fPIC -pthread -std=c++14"
  defines = "-DNDEBUG"

  ::Dir.chdir(FASTTEXT_DIR) do
    sys("g++ #{cppflags} #{defines} -c args.cc") unless ::File.exist?("args.o")
    sys("g++ #{cppflags} #{defines} -c dictionary.cc") unless ::File.exist?("dictionary.o")
    sys("g++ #{cppflags} #{defines} -c productquantizer.cc") unless ::File.exist?("productquantizer.o")
    sys("g++ #{cppflags} #{defines} -c matrix.cc") unless ::File.exist?("matrix.o")
    sys("g++ #{cppflags} #{defines} -c qmatrix.cc") unless ::File.exist?("qmatrix.o")
    sys("g++ #{cppflags} #{defines} -c vector.cc") unless ::File.exist?("vector.o")
    sys("g++ #{cppflags} #{defines} -c model.cc") unless ::File.exist?("model.o")
    sys("g++ #{cppflags} #{defines} -c utils.cc") unless ::File.exist?("utils.o")
    sys("g++ #{cppflags} #{defines} -c fasttext.cc") unless ::File.exist?("fasttext.o")
    sys("g++ #{cppflags} #{defines} -c ffi_fasttext.cc")
    sys("g++ #{cppflags} #{defines} -c curlstream.cc")
    sys("g++ -fPIC -pthread -std=c++14 args.o dictionary.o productquantizer.o matrix.o qmatrix.o vector.o model.o utils.o fasttext.o main.cc -o fasttext") unless ::File.exist?("fasttext")
    sys("g++ -fPIC -pthread -std=c++14 args.o dictionary.o productquantizer.o matrix.o qmatrix.o vector.o model.o utils.o fasttext.o ffi_fasttext.o curlstream.o -lcurl -shared -o libfasttext.#{::FFI::Platform::LIBSUFFIX}")
  end

  unless ::File.exist?(::File.join(FASTTEXT_DIR, "libfasttext.#{::FFI::Platform::LIBSUFFIX}"))
    abort "ERROR: Failed to build fasttext"
  end
end

task :default => :compile_fasttext
